language: node_js
node_js:
  - "node"
sudo: enabled
env:
  - SURGE_LOGIN=guillaumepn@free.fr SURGE_TOKEN=1193b228de0429fa559076ba2cc9b5d3
script:
  - npm run build
deploy:
  provider: surge
  project: ./build/
  domain: didactic-treatment.surge.sh